In [1]:
# user inputs

fileName = "trainHousePrices.csv"
targetVariable = "SalePrice"
numericalFeatures = ["LotArea", "YrSold", "YearBuilt",  "OverallQual", "Fireplaces", "GarageArea"]
categoricalFeatures = ["Neighborhood", "SaleType", "MSSubClass"]

In [2]:
# imports

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import preprocessing
%matplotlib inline

In [3]:
# preprocessing functions

def extendDataframeWithOneHotEncoding(columnName, dataframe, features):
    columnValuesDataframe = dataframe[[columnName]]
    labelEncoder = preprocessing.LabelEncoder()
    labelEncoder.fit(columnValuesDataframe)
    columnValuesEnumeratedList = labelEncoder.classes_
    
    extendTestdataWithOneHotEncoding(columnValuesEnumeratedList, columnName, dataframe)
    features.extend(columnValuesEnumeratedList)
    
def extendTestdataWithOneHotEncoding(newColumns, columnName, dataframe):
    
    columnValuesList = dataframe[columnName]
    for newColumnTitle in newColumns:
        newColumnValues = [1 if x == newColumnTitle else 0 for x in columnValuesList]
        dataframe[newColumnTitle] = newColumnValues

In [4]:
# machine learning algorithms

from sklearn import cross_validation
from sklearn import linear_model
from sklearn.tree import DecisionTreeRegressor

def runLinearModel(X, y):
    linearModelUnderTest = linear_model.LinearRegression()
    cross_validation_scores = cross_validation.cross_val_score(linearModelUnderTest, X, y, cv = 5)
    # accuracy. the higher the better, precision. lower the less variation therefore better 
    return ( np.mean(cross_validation_scores), np.std(cross_validation_scores))

def runRegressionTreeModel(X, y):
    elbowX = range(1,45)
    elbowY = []
    elbowSD = []
    for depth in elbowX:
        regressionDecisionTree = DecisionTreeRegressor(random_state=1, max_depth = depth)
        cross_validation_scores = cross_validation.cross_val_score(regressionDecisionTree, X, y, cv = 5)
        elbowY.append( np.mean(cross_validation_scores) )
        elbowSD.append( np.std(cross_validation_scores) )
    
    maxValue = max(elbowY)
    associatedSd = elbowSD[ elbowY.index(maxValue) ]
    # plt.plot(elbowX, elbowY)
    return (maxValue, associatedSd)

In [5]:
def evaluateInputAgainstModels(train, features, y):
    X = train[features]
    print "Evaluating features: " + str(features)
    
    linearModelResult = runLinearModel(X, y)
    print "Linear Model: " + str(linearModelResult)
    
    regressionTreeResult = runRegressionTreeModel(X, y)
    print "Regression Tree Model: " + str(regressionTreeResult)

In [18]:
def evaluateUsingAll(fileName, targetVariable, numericalFeatures, categoricalFeatures):
    train = pd.read_csv(fileName) 
    features = numericalFeatures
    for categoricalFeature in categoricalFeatures:
        extendDataframeWithOneHotEncoding(categoricalFeature, train, features)
        
    y = train[targetVariable]
    evaluateInputAgainstModels(train, features, y)
    return train[['LotArea', 'YrSold','CollgCr', 'Veenker', 'Crawfor', 'NoRidge', 'WD', 'COD',20, 30,40, 45, 50]]
#    return train[['Blmngtn', 'Blueste', 'BrDale', 'BrkSide', 'ClearCr', 'CollgCr', 'Crawfor', 'Edwards', 'Gilbert', 'IDOTRR', 'MeadowV', 'Mitchel', 'NAmes', 'NPkVill', 'NWAmes', 'NoRidge', 'NridgHt', 'OldTown', 'SWISU', 'Sawyer', 'SawyerW', 'Somerst', 'StoneBr', 'Timber', 'Veenker', 'COD', 'CWD', 'Con', 'ConLD', 'ConLI', 'ConLw', 'New', 'Oth', 'WD', 20, 30, 40, 45, 50, 60, 70, 75, 80, 85, 90, 120, 160, 180, 190, 'Blmngtn', 'Blueste', 'BrDale', 'BrkSide', 'ClearCr', 'CollgCr', 'Crawfor', 'Edwards', 'Gilbert', 'IDOTRR', 'MeadowV', 'Mitchel', 'NAmes', 'NPkVill', 'NWAmes', 'NoRidge', 'NridgHt', 'OldTown', 'SWISU', 'Sawyer', 'SawyerW', 'Somerst', 'StoneBr', 'Timber', 'Veenker', 'COD', 'CWD', 'Con', 'ConLD', 'ConLI', 'ConLw', 'New', 'Oth', 'WD', 20, 30, 40, 45, 50, 60, 70, 75, 80, 85, 90, 120, 160, 180, 190, 'Blmngtn', 'Blueste', 'BrDale', 'BrkSide', 'ClearCr', 'CollgCr', 'Crawfor', 'Edwards', 'Gilbert', 'IDOTRR', 'MeadowV', 'Mitchel', 'NAmes', 'NPkVill', 'NWAmes', 'NoRidge', 'NridgHt', 'OldTown', 'SWISU', 'Sawyer', 'SawyerW', 'Somerst', 'StoneBr', 'Timber', 'Veenker', 'COD', 'CWD', 'Con', 'ConLD', 'ConLI', 'ConLw', 'New', 'Oth', 'WD', 20, 30, 40, 45, 50, 60, 70, 75, 80, 85, 90, 120, 160, 180, 190]]]
    
evaluateUsingAll(fileName, targetVariable, numericalFeatures, categoricalFeatures)

/Users/user/anaconda2/lib/python2.7/site-packages/sklearn/preprocessing/label.py:108: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/user/anaconda2/lib/python2.7/site-packages/sklearn/preprocessing/label.py:108: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/user/anaconda2/lib/python2.7/site-packages/sklearn/preprocessing/label.py:108: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Evaluating features: ['LotArea', 'YrSold', 'YearBuilt', 'OverallQual', 'Fireplaces', 'GarageArea', 'Blmngtn', 'Blueste', 'BrDale', 'BrkSide', 'ClearCr', 'CollgCr', 'Crawfor', 'Edwards', 'Gilbert', 'IDOTRR', 'MeadowV', 'Mitchel', 'NAmes', 'NPkVill', 'NWAmes', 'NoRidge', 'NridgHt', 'OldTown', 'SWISU', 'Sawyer', 'SawyerW', 'Somerst', 'StoneBr', 'Timber', 'Veenker', 'COD', 'CWD', 'Con', 'ConLD', 'ConLI', 'ConLw', 'New', 'Oth', 'WD', 20, 30, 40, 45, 50, 60, 70, 75, 80, 85, 90, 120, 160, 180, 190, 'Blmngtn', 'Blueste', 'BrDale', 'BrkSide', 'ClearCr', 'CollgCr', 'Crawfor', 'Edwards', 'Gilbert', 'IDOTRR', 'MeadowV', 'Mitchel', 'NAmes', 'NPkVill', 'NWAmes', 'NoRidge', 'NridgHt', 'OldTown', 'SWISU', 'Sawyer', 'SawyerW', 'Somerst', 'StoneBr', 'Timber', 'Veenker', 'COD', 'CWD', 'Con', 'ConLD', 'ConLI', 'ConLw', 'New', 'Oth', 'WD', 20, 30, 40, 45, 50, 60, 70, 75, 80, 85, 90, 120, 160, 180, 190, 'Blmngtn', 'Blueste', 'BrDale', 'BrkSide', 'ClearCr', 'CollgCr', 'Crawfor', 'Edwards', 'Gilbert', 'IDOTRR', 'MeadowV', 'Mitchel', 'NAmes', 'NPkVill', 'NWAmes', 'NoRidge', 'NridgHt', 'OldTown', 'SWISU', 'Sawyer', 'SawyerW', 'Somerst', 'StoneBr', 'Timber', 'Veenker', 'COD', 'CWD', 'Con', 'ConLD', 'ConLI', 'ConLw', 'New', 'Oth', 'WD', 20, 30, 40, 45, 50, 60, 70, 75, 80, 85, 90, 120, 160, 180, 190, 'Blmngtn', 'Blueste', 'BrDale', 'BrkSide', 'ClearCr', 'CollgCr', 'Crawfor', 'Edwards', 'Gilbert', 'IDOTRR', 'MeadowV', 'Mitchel', 'NAmes', 'NPkVill', 'NWAmes', 'NoRidge', 'NridgHt', 'OldTown', 'SWISU', 'Sawyer', 'SawyerW', 'Somerst', 'StoneBr', 'Timber', 'Veenker', 'COD', 'CWD', 'Con', 'ConLD', 'ConLI', 'ConLw', 'New', 'Oth', 'WD', 20, 30, 40, 45, 50, 60, 70, 75, 80, 85, 90, 120, 160, 180, 190, 'Blmngtn', 'Blueste', 'BrDale', 'BrkSide', 'ClearCr', 'CollgCr', 'Crawfor', 'Edwards', 'Gilbert', 'IDOTRR', 'MeadowV', 'Mitchel', 'NAmes', 'NPkVill', 'NWAmes', 'NoRidge', 'NridgHt', 'OldTown', 'SWISU', 'Sawyer', 'SawyerW', 'Somerst', 'StoneBr', 'Timber', 'Veenker', 'COD', 'CWD', 'Con', 'ConLD', 'ConLI', 'ConLw', 'New', 'Oth', 'WD', 20, 30, 40, 45, 50, 60, 70, 75, 80, 85, 90, 120, 160, 180, 190, 'Blmngtn', 'Blueste', 'BrDale', 'BrkSide', 'ClearCr', 'CollgCr', 'Crawfor', 'Edwards', 'Gilbert', 'IDOTRR', 'MeadowV', 'Mitchel', 'NAmes', 'NPkVill', 'NWAmes', 'NoRidge', 'NridgHt', 'OldTown', 'SWISU', 'Sawyer', 'SawyerW', 'Somerst', 'StoneBr', 'Timber', 'Veenker', 'COD', 'CWD', 'Con', 'ConLD', 'ConLI', 'ConLw', 'New', 'Oth', 'WD', 20, 30, 40, 45, 50, 60, 70, 75, 80, 85, 90, 120, 160, 180, 190]
Linear Model: (0.77174356330985094, 0.03896862697255056)
Regression Tree Model: (0.70512818811161571, 0.061541359482155208)

,LotArea,YrSold,CollgCr,Veenker,Crawfor,NoRidge,WD,COD,20,30,40,45,50
0,8450,2008,1,0,0,0,1,0,0,0,0,0,0
1,9600,2007,0,1,0,0,1,0,1,0,0,0,0
2,11250,2008,1,0,0,0,1,0,0,0,0,0,0
3,9550,2006,0,0,1,0,1,0,0,0,0,0,0
4,14260,2008,0,0,0,1,1,0,0,0,0,0,0
5,14115,2009,0,0,0,0,1,0,0,0,0,0,1
6,10084,2007,0,0,0,0,1,0,1,0,0,0,0
7,10382,2009,0,0,0,0,1,0,0,0,0,0,0
8,6120,2008,0,0,0,0,1,0,0,0,0,0,1
9,7420,2008,0,0,0,0,1,0,0,0,0,0,0
10,11200,2008,0,0,0,0,1,0,1,0,0,0,0
11,11924,2006,0,0,0,0,0,0,0,0,0,0,0
12,12968,2008,0,0,0,0,1,0,1,0,0,0,0
13,10652,2007,1,0,0,0,0,0,1,0,0,0,0
14,10920,2008,0,0,0,0,1,0,1,0,0,0,0
15,6120,2007,0,0,0,0,1,0,0,0,0,1,0
16,11241,2010,0,0,0,0,1,0,1,0,0,0,0
17,10791,2006,0,0,0,0,1,0,0,0,0,0,0
18,13695,2008,0,0,0,0,1,0,1,0,0,0,0
19,7560,2009,0,0,0,0,0,1,1,0,0,0,0
20,14215,2006,0,0,0,0,0,0,0,0,0,0,0
21,7449,2007,0,0,0,0,1,0,0,0,0,1,0
22,9742,2008,1,0,0,0,1,0,1,0,0,0,0
23,4224,2007,0,0,0,0,1,0,0,0,0,0,0
24,8246,2010,0,0,0,0,1,0,1,0,0,0,0
25,14230,2009,0,0,0,0,1,0,1,0,0,0,0
26,7200,2010,0,0,0,0,1,0,1,0,0,0,0
27,11478,2010,0,0,0,0,1,0,1,0,0,0,0
28,16321,2006,0,0,0,0,1,0,1,0,0,0,0
29,6324,2008,0,0,0,0,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430,21930,2006,0,0,0,0,1,0,0,0,0,0,0
1431,4928,2009,0,0,0,0,1,0,0,0,0,0,0
1432,10800,2007,0,0,0,0,1,0,0,1,0,0,0
1433,10261,2008,0,0,0,0,1,0,0,0,0,0,0
1434,17400,2006,0,0,0,0,1,0,1,0,0,0,0
1435,8400,2008,0,0,0,0,0,1,1,0,0,0,0
1436,9000,2007,0,0,0,0,1,0,1,0,0,0,0
1437,12444,2008,0,0,0,0,0,0,1,0,0,0,0
1438,7407,2010,0,0,0,0,1,0,1,0,0,0,0
1439,11584,2007,0,0,0,0,1,0,0,0,0,0,0
1440,11526,2008,0,0,1,0,1,0,0,0,0,0,0
1441,4426,2008,1,0,0,0,1,0,0,0,0,0,0
1442,11003,2009,0,0,0,0,1,0,0,0,0,0,0
1443,8854,2009,0,0,0,0,1,0,0,1,0,0,0
1444,8500,2007,1,0,0,0,1,0,1,0,0,0,0
1445,8400,2007,0,0,0,0,1,0,0,0,0,0,0
1446,26142,2010,0,0,0,0,1,0,1,0,0,0,0
1447,10000,2007,1,0,0,0,1,0,0,0,0,0,0
1448,11767,2007,0,0,0,0,1,0,0,0,0,0,1
1449,1533,2006,0,0,0,0,1,0,0,0,0,0,0
1450,9000,2009,0,0,0,0,1,0,0,0,0,0,0
1451,9262,2009,0,0,0,0,0,0,1,0,0,0,0
1452,3675,2006,0,0,0,0,1,0,0,0,0,0,0
1453,17217,2006,0,0,0,0,1,0,1,0,0,0,0
1454,7500,2009,0,0,0,0,1,0,1,0,0,0,0
1455,7917,2007,0,0,0,0,1,0,0,0,0,0,0
1456,13175,2010,0,0,0,0,1,0,1,0,0,0,0
1457,9042,2010,0,0,1,0,1,0,0,0,0,0,0
1458,9717,2010,0,0,0,0,1,0,1,0,0,0,0
1459,9937,2008,0,0,0,0,1,0,1,0,0,0,0

In [12]:
train = pd.read_csv(fileName)
train[:5][ ['LotArea',"Neighborhood", "SaleType", "MSSubClass" ,'YrSold', 'YearBuilt', 'OverallQual', 'Fireplaces', 'GarageArea']]

,LotArea,Neighborhood,SaleType,MSSubClass,YrSold,YearBuilt,OverallQual,Fireplaces,GarageArea
0,8450,CollgCr,WD,60,2008,2003,7,0,548
1,9600,Veenker,WD,20,2007,1976,6,1,460
2,11250,CollgCr,WD,60,2008,2001,7,1,608
3,9550,Crawfor,WD,70,2006,1915,7,1,642
4,14260,NoRidge,WD,60,2008,2000,8,1,836